In [80]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question See github Page

In [81]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.4.1+cu121


## Intrpduction to Tensors

### Creating Tensor

In [82]:
# Scalar
scalar = torch.tensor(7)
print(scalar)

tensor(7)


In [83]:
# Scalar is just a single number
scalar.ndim

0

In [84]:
# Turn Tensor back as Python intiger
scalar.item()

7

In [85]:
# Vector
vector = torch.tensor([7, 17])
print(vector)

tensor([ 7, 17])


In [86]:
# number of Square BracketS = Dimension
vector.ndim

1

In [87]:
vector.shape

torch.Size([2])

In [88]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [89]:
  MATRIX.ndim

2

In [90]:
MATRIX.shape

torch.Size([2, 2])

In [91]:
MATRIX[0]

tensor([7, 8])

In [92]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [4, 6, 10]],

                       [[11, 12, 13],
                        [24, 49, 75],
                        [40, 90, 83]]])
TENSOR

tensor([[[ 1,  2,  3],
         [ 3,  6,  9],
         [ 4,  6, 10]],

        [[11, 12, 13],
         [24, 49, 75],
         [40, 90, 83]]])

In [93]:
TENSOR.ndim

3

In [94]:
TENSOR.shape

torch.Size([2, 3, 3])

In [95]:
TENSOR[1]

tensor([[11, 12, 13],
        [24, 49, 75],
        [40, 90, 83]])

### Random Tensors?

Why Random Tensors?

Random tensors are important because the way many neural networks learn is that they start with random numbers and then adjust those random numbers to better represent the data.

` Start with random numbers -> look at data -> update random numbers`





### torch.rand
Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)

See Documantation on https://pytorch.org/docs/stable/generated/torch.rand.html

In [96]:
#Create Random Tensors of shape (3, 4)

random_tensor = torch.rand(3, 4)
print(random_tensor)

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])


In [97]:
random_tensor.ndim

2

In [98]:
#more examples of random tensor

TENSOR_1 = torch.rand(1, 10, 10)
print(TENSOR_1)
print(f'number of dimensions: {TENSOR_1.ndim}')

tensor([[[0.1053, 0.2695, 0.3588, 0.1994, 0.5472, 0.0062, 0.9516, 0.0753,
          0.8860, 0.5832],
         [0.3376, 0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644,
          0.7104, 0.9464],
         [0.7890, 0.2814, 0.7886, 0.5895, 0.7539, 0.1952, 0.0050, 0.3068,
          0.1165, 0.9103],
         [0.6440, 0.7071, 0.6581, 0.4913, 0.8913, 0.1447, 0.5315, 0.1587,
          0.6542, 0.3278],
         [0.6532, 0.3958, 0.9147, 0.2036, 0.2018, 0.2018, 0.9497, 0.6666,
          0.9811, 0.0874],
         [0.0041, 0.1088, 0.1637, 0.7025, 0.6790, 0.9155, 0.2418, 0.1591,
          0.7653, 0.2979],
         [0.8035, 0.3813, 0.7860, 0.1115, 0.2477, 0.6524, 0.6057, 0.3725,
          0.7980, 0.8399],
         [0.1374, 0.2331, 0.9578, 0.3313, 0.3227, 0.0162, 0.2137, 0.6249,
          0.4340, 0.1371],
         [0.5117, 0.1585, 0.0758, 0.2247, 0.0624, 0.1816, 0.9998, 0.5944,
          0.6541, 0.0337],
         [0.1716, 0.3336, 0.5782, 0.0600, 0.2846, 0.2007, 0.5014, 0.3139,
          0.4654,

In [99]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # height, widht, color channels(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and ones

In [100]:
# Create a tensor of all zeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [101]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [102]:
# Create tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [103]:
ones.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [104]:
# Use torch.arange()
one_to_ten = torch.arange(1, 10)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [105]:
# another impleamentation
one_to_nine = torch.arange(start=1, end=10, step=1)
one_to_nine

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [106]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatype

**NOTE:** Tensor datatypes is one of the 3 big errors you'll run into with Pytorch and deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [107]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # What datatype is the tensor(e.g. float32 or float16)
                               device=None,
                               requires_grad=False)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [108]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [109]:
# Create a tensor and find out details about it
some_tensor = torch.rand([3, 4])
print(some_tensor)
print(some_tensor.shape)
print(some_tensor.size)

(tensor([[0.3507, 0.6683, 0.4601, 0.9545],
         [0.1936, 0.8199, 0.3752, 0.6261],
         [0.6456, 0.1400, 0.8216, 0.6671]]),
 torch.Size([3, 4]),
 <function Tensor.size>)

In [110]:
# Details about this tensor
print(some_tensor)
print(f"\nDatatype of the tensor: {some_tensor.dtype}")
print(f"shape of tensor: {some_tensor.shape}")
print(f"Device of the tensor: {some_tensor.device}") # The Default device is cpu

tensor([[0.3507, 0.6683, 0.4601, 0.9545],
        [0.1936, 0.8199, 0.3752, 0.6261],
        [0.6456, 0.1400, 0.8216, 0.6671]])
Datatype of the tensor: torch.float32
shape of tensor: torch.Size([3, 4])
Device of the tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multipication
* Division
* Matrix Multipication

In [111]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [112]:
# Try out Pytorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

### Matrix Multipication

Two main ways of performing multipication in neural networks and deep learning:

1. Element-wise Multipication
2. Matrix Multipication (dot product)


There are Two main rules that performing matrix multipication needs to satisfy:
1. The **inner dimension** must match.
2. The resulting matrix has the shape of the **outer dimensions**

In [113]:
# Element-wise Multipication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [114]:
# Matrix Multipication
%%time
torch.matmul(tensor, tensor)

CPU times: user 147 µs, sys: 0 ns, total: 147 µs
Wall time: 159 µs


tensor(14)

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [115]:
# Create a tensor
x = torch.arange(0, 100, 10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [116]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [117]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

**Note:** the torch.mean() function requires a tensor of float32 datatype to work.

In [118]:
# Find the mean -> torch tensor mean can't work with long datatype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [119]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

In [120]:
%%time
torch.sum(x)

CPU times: user 86 µs, sys: 3 µs, total: 89 µs
Wall time: 93.9 µs


tensor(450)

In [121]:
%%time
x.sum()

CPU times: user 101 µs, sys: 4 µs, total: 105 µs
Wall time: 109 µs


tensor(450)

### Finding the positional min and max

In [122]:
# Find the position in the tensor that has the minimum value with argmin()
x.argmin()

tensor(0)

In [123]:
# Find the position in the tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

### Reshaping, Stacking, Squeezing and Unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other.
* Squeez - removes all `1` dimensions from a tensor.
* Unsqueez - add a `1` dimension to a target tensor.
* Permute - Return a view of the input with dimensions permuted(swapped) in a certain way.

In [124]:
# Let's create a tensor
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [125]:
# Add an extra dimension:
x_reshaped = x.reshape((10, 1))
x_reshaped_T = x.reshape((1, 10))
print(x_reshaped)
print(f"\n{x_reshaped.shape}")
print(f"\n{x_reshaped_T}")

tensor([[ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.]])

torch.Size([10, 1])

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])


**Note:** View shares the memory with original tensor.

Changing Z changes x (because a view of a tensor shares the same memory as the original)

In [126]:
# Change View
z = x.view(1, 10)
print(z)
print(z.shape)

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [127]:
z[:, 0] = 5
print(z)
print(x)

(tensor([[ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 tensor([ 5.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]))

In [128]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=-1)
x_stacked

tensor([[ 5.,  5.,  5.,  5.],
        [ 2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.],
        [10., 10., 10., 10.]])

## Indexing (Selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [129]:
# Create a Tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
print(x)
print(f"\n{x.shape}")

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [130]:
# Lets index our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [131]:
# Lets index on middle bracket (dim=1)
print(x[0][0]) # Or
print(x[0, 0])

tensor([1, 2, 3])
tensor([1, 2, 3])


In [132]:
# Let's index on the most inner bracket (last dimension)
print(x[0][0][0]) # Or
print(x[0, 0, 0])

tensor(1)
tensor(1)


In [133]:
# Playing with indexes:
print(x)
print(x[0, 1])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([4, 5, 6])


In [134]:
print(x)
print(x[0, 0, 1])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor(2)


In [135]:
print(x)
print(x[0, 1, 0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor(4)


In [136]:
print(x)
print(x[0, 2, 0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor(7)


In [137]:
# You can also use ":" to  select "all" of the target dimension
print(x)
print(x[:, 0]) # First row
print(x[:, 1]) # Second row
print(x[:, 2]) # Third row

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 2, 3]])
tensor([[4, 5, 6]])
tensor([[7, 8, 9]])


In [138]:
# Get all values of 0th and 1st dimension but only index 1 of 2nd dimension
print(x)
print(x[:, :, 1]) # Second coloumn

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[2, 5, 8]])


In [139]:
# Get all values of 0th and 1st dimension but only index 0 of 2nd dimension
print(x)
print(x[:, :, 0])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[1, 4, 7]])


In [140]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
print(x)
print(x[:, 1, 1])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([5])


In [141]:
# Get all values of 0th and 1st dimension but only index 2 of seconed dimension
print(x)
print(x[:, :, 2])

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])
tensor([[3, 6, 9]])


## PyTorch tensors and NumPy

* Data in NumPy, want in PyTorch tensor -> torch.from_numpy(ndarray)
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [142]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 10.0)
tensor = torch.from_numpy(array)
print(f"Numpy array: {array}")
print(f"Numpy array converted to torch tensor: {tensor}")

Numpy array: [1. 2. 3. 4. 5. 6. 7. 8. 9.]
Numpy array converted to torch tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)


In [143]:
# Let's check the data type of numpy array and torch tensor:
print(f"Datatype of numpy array is {array.dtype}")
print(f"Datatype of torch tensor is {tensor.dtype}")

Datatype of numpy array is float64
Datatype of torch tensor is torch.float64


In [144]:
# Create a Random tensor and check it's datatype
x = torch.arange(1., 10.)
x.dtype

torch.float32

 - As you can see, the datatype of *numpy-created-array* is allways **float64** and when you convert it to a tensor, it will be as the same datatype as before.

 - but a torch-created-tensor will has a type of **torch.float32**.

 **WARNING:* When converting from NumPy -> PyTorch, PyTorch reflects numpy's default datatype of float64 unless specified otherwise.

In [145]:
tensor.type(torch.float32)
tensor.dtype

torch.float64

In [146]:
# Change the Value of array, what will this do to 'tensor'?
array = array + 1
print(array)
print(tensor)
print("Tensor does not share memory with numpy array")

[ 2.  3.  4.  5.  6.  7.  8.  9. 10.]
tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64)
Tensor does not share memory with numpy array


In [147]:
# Tensor to Numpy array
tensor = torch.ones(7) # datatype -> float32
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

The datatype of the Tensor -> Numpy array is as the same as the Tensor's datatype (default float32)

In [148]:
# Change the Tensor, What happens to 'numpy_tensor'?
tensor = tensor + 1
print(tensor)
print(numpy_tensor)

tensor([2., 2., 2., 2., 2., 2., 2.])
[1. 1. 1. 1. 1. 1. 1.]


So Tensor arrays does not share memory with converted-numpy-array.

For more examples and exercises, Check out https://pytorch.org/tutorials/beginner/examples_tensor/polynomial_numpy.html .

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of data of the data -> again -> again -> again ..`

To reduce randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what a random seed does is "flavour" the randomness.

More information on https://pytorch.org/docs/stable/notes/randomness.html

In [149]:
torch.rand(3, 3) # Every time we run this cell it gives us different numbers

tensor([[0.1167, 0.3571, 0.5386],
        [0.2662, 0.1353, 0.1664],
        [0.5620, 0.3337, 0.3034]])

In [150]:
import torch

# Create two random tensors
tensor_A = torch.rand(3, 4)
tensor_B = torch.rand(3, 4)

print(tensor_A)
print(f"\n{tensor_B}")
print(f"\n{tensor_A == tensor_B}")

tensor([[0.6037, 0.1452, 0.8953, 0.4402],
        [0.7838, 0.2089, 0.1943, 0.7621],
        [0.4492, 0.9147, 0.4331, 0.7791]])

tensor([[0.1290, 0.4005, 0.3250, 0.1490],
        [0.6707, 0.9793, 0.3283, 0.3403],
        [0.6935, 0.0863, 0.0825, 0.2319]])

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [151]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 42 # 42 is the common one but you can use every number you want.

# Create Random Tensors
torch.manual_seed(RANDOM_SEED)
tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
tensor_D = torch.rand(3, 4)

print(tensor_C)
print(f"\n{tensor_D}")
print(f"\n{tensor_C == tensor_D}")

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensor and PyTorch objects on the GPUs (and making faster computations)

GPU = faster computation on numbers, thanks to CUDA + NVIDIA harware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options.
3. Use cloud computing - GCP, AWS, Azure, these services aloow you to rent computers on the cloud an access them.

For 2 and 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this refer to PyTorch setup documentation.

- Start Locally: https://pytorch.org/get-started/locally/

- Start on Cloud services: https://pytorch.org/get-started/cloud-partners/

In [152]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2. Check for GPU acess with PyTorch

In [154]:
import torch

torch.cuda.is_available()

False

In [155]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

For PyTorch since it's capble of running compute on the GPU or CPU, it's a best practice to setup device agnostic code:
https://pytorch.org/docs/stable/notes/cuda.html#best-practices

In [156]:
# Count the number of devices -> device_count()
torch.cuda.device_count()

0

## 3. Putting tensors (and models) on the GPU

The reason we want out tensors/models on the GPU is because using a GPU results in faster computations.

In [157]:
# Create a tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [159]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu, tensor.device # depends on your device in google colab

(tensor([1, 2, 3]), device(type='cpu'))

### 4. Moving tensors back to the CPU

For example, numpy only works with CPU. So you need to conver GPU-tensors to CPU-tensors.

In [161]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy() # IF you are on GPU, it will end to TypeError

array([1, 2, 3])

In [165]:
# To fix the GPU tensor with NumPy issue, wew can first set it on the CPU

tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])